# Site settings
title: TÃœBIX
email: info@tuebix.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tuebix.org" # the base hostname & protocol for your site

collections: 
  talks:
    output: true
