# Site settings
title: TÃ¼bix
email: info@tuebix.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.tuebix.org" # the base hostname & protocol for your site

collections:
  talks:
    output: true

# https://help.github.com/articles/redirects-on-github-pages/
plugins:
  - jekyll-redirect-from
